-- =====================================================================
-- V11: 시책 마스터 + 변경 이력 (설계서 §3.6, Phase 13)
-- 요율 마스터(COMM_RATE)와 동일한 유효기간+버전+승인 패턴. 대상 필터(insurer/product/channel)는
-- NULL = 전체(와일드카드). 조건식은 SpEL(샌드박스 평가). 겹침 불변식은 같은 incentive_cd에 대해
-- 승인 워크플로(앱 계층)가 강제한다 — 동시성 최종 심판(function-based unique index)은 후속 과제.
-- =====================================================================

CREATE TABLE INCENTIVE_MST (
    incentive_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incentive_cd   VARCHAR2(30)   NOT NULL,       -- 시책 식별 코드 (버전 키)
    insurer_cd     VARCHAR2(10),                  -- NULL = 전체 보험사
    product_key    VARCHAR2(40),                  -- NULL = 전체 상품
    channel        VARCHAR2(20),                  -- NULL = 전체 채널
    condition_expr VARCHAR2(1000) NOT NULL,       -- SpEL 조건식 (등록·승인 시 샌드박스 검증)
    payout_kind    VARCHAR2(16)   NOT NULL,       -- FIXED / PREMIUM_RATE
    fixed_amount   NUMBER(15),                    -- FIXED 전용
    premium_rate   NUMBER(9,6),                   -- PREMIUM_RATE 전용
    apply_from     DATE           NOT NULL,
    apply_to       DATE           DEFAULT DATE '9999-12-31' NOT NULL,
    version_no     NUMBER         NOT NULL,
    status         VARCHAR2(10)   NOT NULL,       -- DRAFT/ACTIVE/SUPERSEDED
    created_by     VARCHAR2(20),
    created_at     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    approved_by    VARCHAR2(20),
    approved_at    TIMESTAMP,
    CONSTRAINT ck_incentive_status CHECK (status IN ('DRAFT','ACTIVE','SUPERSEDED')),
    CONSTRAINT ck_incentive_kind CHECK (payout_kind IN ('FIXED','PREMIUM_RATE'))
);

-- 기준일 유효 ACTIVE 조회용
CREATE INDEX ix_incentive_active ON INCENTIVE_MST (status, apply_from, apply_to);
-- 버전 이력 조회용
CREATE INDEX ix_incentive_cd ON INCENTIVE_MST (incentive_cd, version_no);

CREATE TABLE INCENTIVE_CHANGE_HIST (
    change_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incentive_id NUMBER       NOT NULL,
    change_type  VARCHAR2(12) NOT NULL,
    old_apply_to DATE,
    new_apply_to DATE,
    old_status   VARCHAR2(10),
    new_status   VARCHAR2(10),
    changed_by   VARCHAR2(20),
    changed_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_incentive_hist FOREIGN KEY (incentive_id) REFERENCES INCENTIVE_MST (incentive_id),
    CONSTRAINT ck_incentive_change_type CHECK (change_type IN ('TRIM','SUPERSEDE','ACTIVATE','DISCARD'))
);
CREATE INDEX ix_incentive_hist ON INCENTIVE_CHANGE_HIST (incentive_id);

-- 승인 워크플로 채번 (identity와 분리된 대역 — 시드/수기 충돌 차단, 요율의 COMM_RATE_ADMIN_SEQ와 동일 규약)
CREATE SEQUENCE INCENTIVE_ADMIN_SEQ START WITH 1000000 INCREMENT BY 1;
