-- =====================================================================
-- V1: 룰/마스터 테이블 (설계서 §5.1 ~ §5.3)
-- 원칙: 요율·한도·지급률은 전부 유효기간(apply_from/apply_to)을 가진 버전 데이터.
-- 이식성: H2(MODE=Oracle)와 Oracle 19c+ 겸용 문법만 사용한다.
--   * Oracle 전용 기능(파티셔닝, IS JSON 체크)은 Oracle 배포 시 별도 스크립트로 보강.
-- =====================================================================

-- 5.1 수수료 유형 마스터 (한도 포함 여부/반올림 정책도 유효기간 데이터)
CREATE TABLE COMM_TYPE_MST (
    comm_type       VARCHAR2(20)  NOT NULL,
    apply_from      DATE          NOT NULL,
    apply_to        DATE          DEFAULT DATE '9999-12-31' NOT NULL,
    limit_included  CHAR(1)       NOT NULL,              -- 1200% 한도 합산 대상 Y/N
    rounding_policy VARCHAR2(20)  NOT NULL,              -- RoundingPolicy enum 이름
    clawback_target CHAR(1)       NOT NULL,              -- 환수 대상 여부 Y/N
    CONSTRAINT pk_comm_type PRIMARY KEY (comm_type, apply_from),
    CONSTRAINT ck_comm_type_limit CHECK (limit_included IN ('Y', 'N')),
    CONSTRAINT ck_comm_type_clawback CHECK (clawback_target IN ('Y', 'N'))
);

-- 5.2 요율 (INBOUND=보험사→GA 수령 / OUTBOUND=GA→설계사 지급)
CREATE TABLE COMM_RATE (
    rate_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction       VARCHAR2(8)   NOT NULL,
    insurer_cd      VARCHAR2(10)  NOT NULL,
    product_key     VARCHAR2(40)  NOT NULL,
    comm_type       VARCHAR2(20)  NOT NULL,
    installment_no  NUMBER(3),                           -- 회차 (NULL=일시 지급형)
    rate            NUMBER(9,6)   NOT NULL,
    apply_from      DATE          NOT NULL,
    apply_to        DATE          DEFAULT DATE '9999-12-31' NOT NULL,
    version_no      NUMBER        NOT NULL,
    status          VARCHAR2(10)  NOT NULL,              -- DRAFT/ACTIVE/SUPERSEDED
    created_by      VARCHAR2(20),
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    approved_by     VARCHAR2(20),
    approved_at     TIMESTAMP,
    CONSTRAINT ck_comm_rate_dir CHECK (direction IN ('INBOUND', 'OUTBOUND')),
    CONSTRAINT ck_comm_rate_status CHECK (status IN ('DRAFT', 'ACTIVE', 'SUPERSEDED'))
);
-- ACTIVE 버전의 (direction, insurer, product, type, installment, apply_from) 유일성은
-- 승인 워크플로(애플리케이션 계층)에서 강제한다. (부분 유니크 인덱스는 DB 이식성 문제)
CREATE INDEX ix_comm_rate_lookup
    ON COMM_RATE (direction, insurer_cd, product_key, comm_type, apply_from);

-- 5.3 설계사 등급별 지급률
CREATE TABLE AGENT_PAYOUT_RATE (
    grade_cd    VARCHAR2(10) NOT NULL,
    comm_type   VARCHAR2(20) NOT NULL,
    payout_rate NUMBER(9,6)  NOT NULL,
    apply_from  DATE         NOT NULL,
    apply_to    DATE         DEFAULT DATE '9999-12-31' NOT NULL,
    CONSTRAINT pk_payout PRIMARY KEY (grade_cd, comm_type, apply_from)
);

-- 1200% 한도 룰 (한도 배수 12.00 하드코딩 금지 — 채널·계약일 기준 버전 데이터)
CREATE TABLE LIMIT_RULE (
    rule_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_type   VARCHAR2(20) NOT NULL,               -- CAPTIVE(전속)/GA_TO_AGENT 등
    limit_multiple NUMBER(6,2)  NOT NULL,               -- 12.00
    fy_window_months NUMBER(3)  NOT NULL,               -- 초년도 윈도우(개월) — 미결정 §11.1 파라미터
    over_limit_action VARCHAR2(20) NOT NULL,            -- CUT / DEFER_AFTER_FY — 미결정 §11.3 파라미터
    clawback_restores CHAR(1)   NOT NULL,               -- 환수 시 한도 여유 복원 여부 — 미결정 파라미터
    apply_from     DATE         NOT NULL,               -- 계약 체결일 기준 적용 개시
    apply_to       DATE         DEFAULT DATE '9999-12-31' NOT NULL,
    CONSTRAINT ck_limit_rule_action CHECK (over_limit_action IN ('CUT', 'DEFER_AFTER_FY')),
    CONSTRAINT ck_limit_rule_restore CHECK (clawback_restores IN ('Y', 'N'))
);
