-- =====================================================================
-- V2: 계약 이벤트 + 수수료 계산 결과 원장 (설계서 §5.4 ~ §5.5)
-- =====================================================================

-- 5.4 계약 이벤트 (원천, 불변. 멱등키로 중복 수신 차단)
CREATE TABLE POLICY_EVENT (
    event_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key      VARCHAR2(100) NOT NULL,
    policy_no      VARCHAR2(30)  NOT NULL,
    insurer_cd     VARCHAR2(10)  NOT NULL,
    product_key    VARCHAR2(40)  NOT NULL,
    event_type     VARCHAR2(20)  NOT NULL,   -- NEW/PAYMENT/CANCEL/LAPSE/REVIVE/REDUCE/WITHDRAW/CORRECT
    event_date     DATE          NOT NULL,   -- 업무 발생일 (룰 기준일 산정에 사용)
    contract_date  DATE          NOT NULL,   -- 계약 체결일 (한도/분급/환수 룰 버전 기준일)
    agent_id       VARCHAR2(20)  NOT NULL,   -- 모집 설계사
    monthly_premium NUMBER(15)   NOT NULL,   -- 월납환산보험료
    payment_amount NUMBER(15),               -- 회차 납입액
    installment_no NUMBER(3),
    payload        CLOB,                     -- 원문 JSON (Oracle 배포 시 IS JSON 체크 추가)
    received_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    process_status VARCHAR2(10)  DEFAULT 'PENDING' NOT NULL,  -- PENDING/PROCESSED/FAILED/SKIPPED
    CONSTRAINT uq_policy_event_key UNIQUE (event_key),
    CONSTRAINT ck_event_type CHECK (event_type IN
        ('NEW','PAYMENT','CANCEL','LAPSE','REVIVE','REDUCE','WITHDRAW','CORRECT')),
    CONSTRAINT ck_event_status CHECK (process_status IN
        ('PENDING','PROCESSED','FAILED','SKIPPED'))
);
CREATE INDEX ix_policy_event_policy ON POLICY_EVENT (policy_no, event_type);
CREATE INDEX ix_policy_event_status ON POLICY_EVENT (process_status);

-- 5.5 수수료 계산 결과 (불변 원장)
--   * 생성 후 UPDATE는 status 전이만 허용. 정정은 reversal(음수) + 신규 레코드.
--   * Oracle 배포 시: PARTITION BY RANGE (close_ym) INTERVAL + rule_versions/calc_trace IS JSON 체크.
CREATE TABLE COMM_CALC (
    calc_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       NUMBER        NOT NULL,
    policy_no      VARCHAR2(30)  NOT NULL,
    recipient_type VARCHAR2(10)  NOT NULL,   -- AGENT / ORG
    recipient_id   VARCHAR2(20)  NOT NULL,
    comm_type      VARCHAR2(20)  NOT NULL,
    base_amount    NUMBER(15)    NOT NULL,   -- 산출 기준액
    applied_rate   NUMBER(9,6),
    calc_amount    NUMBER(15)    NOT NULL,   -- 환수는 음수
    limit_cut_amt  NUMBER(15)    DEFAULT 0 NOT NULL,  -- 1200% 한도로 삭감/이연된 금액
    close_ym       VARCHAR2(6)   NOT NULL,   -- 귀속 마감월
    status         VARCHAR2(12)  NOT NULL,   -- CALCULATED/CONFIRMED/PAID/REVERSED
    reversal_of    NUMBER,                   -- 취소분개 원본 참조
    rule_versions  CLOB,                     -- 사용한 룰버전 박제 (JSON)
    calc_trace     CLOB,                     -- 단계별 중간값 (JSON)
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_calc_event FOREIGN KEY (event_id) REFERENCES POLICY_EVENT (event_id),
    CONSTRAINT fk_calc_reversal FOREIGN KEY (reversal_of) REFERENCES COMM_CALC (calc_id),
    CONSTRAINT ck_calc_recipient CHECK (recipient_type IN ('AGENT', 'ORG')),
    CONSTRAINT ck_calc_status CHECK (status IN ('CALCULATED','CONFIRMED','PAID','REVERSED'))
);
CREATE INDEX ix_comm_calc_policy ON COMM_CALC (policy_no, recipient_id);
CREATE INDEX ix_comm_calc_close ON COMM_CALC (close_ym, status);
CREATE INDEX ix_comm_calc_event ON COMM_CALC (event_id);
