-- =====================================================================
-- V3: 1200% 한도 원장 (설계서 §5.6)
-- 불변식: accum_paid <= limit_amount, accum_paid = SUM(LIMIT_LEDGER_DTL.amount)
-- =====================================================================

CREATE TABLE LIMIT_LEDGER (
    ledger_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_no       VARCHAR2(30) NOT NULL,
    agent_id        VARCHAR2(20) NOT NULL,
    contract_date   DATE         NOT NULL,
    fy_start        DATE         NOT NULL,   -- 초년도 시작 (규정 정의 확인 — 파라미터)
    fy_end          DATE         NOT NULL,
    monthly_premium NUMBER(15)   NOT NULL,   -- 월납환산보험료 (감액 시 이력과 함께 갱신)
    limit_multiple  NUMBER(6,2)  NOT NULL,   -- LIMIT_RULE에서 복사 (하드코딩 금지)
    limit_amount    NUMBER(15)   NOT NULL,
    accum_paid      NUMBER(15)   DEFAULT 0 NOT NULL, -- 한도 포함 항목 누적 (환수 시 차감)
    rule_version_id NUMBER       NOT NULL,
    lock_version    NUMBER       DEFAULT 0 NOT NULL, -- 낙관적 락
    CONSTRAINT uq_limit UNIQUE (policy_no, agent_id)
);

-- 누적의 근거 (calc_id 단위 가감 내역)
--   posting_seq: 원장 내 단조 증가 전기 순번 (설계서 §5.6 v1.1) — replay 재구성의 유일한 정렬 기준.
--   채번은 원장 락(FOR UPDATE) 보유 상태에서만 한다(MAX+1). posted_at은 참고용이며
--   순서 판단에 사용을 금지한다 (부록 B-8).
CREATE TABLE LIMIT_LEDGER_DTL (
    ledger_id   NUMBER     NOT NULL,
    posting_seq NUMBER     NOT NULL,
    calc_id     NUMBER     NOT NULL,
    amount      NUMBER(15) NOT NULL,
    posted_at   TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_limit_dtl PRIMARY KEY (ledger_id, posting_seq),
    CONSTRAINT fk_limit_dtl_ledger FOREIGN KEY (ledger_id) REFERENCES LIMIT_LEDGER (ledger_id),
    CONSTRAINT fk_limit_dtl_calc FOREIGN KEY (calc_id) REFERENCES COMM_CALC (calc_id)
);

-- 월납보험료 변경(감액/증액)에 따른 한도 재산정 이력
CREATE TABLE LIMIT_LEDGER_HIST (
    hist_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id       NUMBER      NOT NULL,
    event_id        NUMBER,
    monthly_premium NUMBER(15)  NOT NULL,
    limit_amount    NUMBER(15)  NOT NULL,
    changed_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    reason          VARCHAR2(200),
    CONSTRAINT fk_limit_hist_ledger FOREIGN KEY (ledger_id) REFERENCES LIMIT_LEDGER (ledger_id)
);
