-- =====================================================================
-- V4: 분급 커브 + 분급 스케줄 (설계서 §5.7, §6.2 — 2027.1 대비)
-- 커브 자체가 데이터: 4년 커브 → 7년 커브 확장은 레코드 추가만으로 흡수한다.
-- =====================================================================

CREATE TABLE DEFERRAL_CURVE (
    curve_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curve_name VARCHAR2(50) NOT NULL,
    apply_from DATE         NOT NULL,   -- 계약 체결일 기준 적용 개시
    apply_to   DATE         DEFAULT DATE '9999-12-31' NOT NULL
);

CREATE TABLE DEFERRAL_CURVE_DTL (
    curve_id  NUMBER      NOT NULL,
    month_no  NUMBER(3)   NOT NULL,     -- 계약 후 경과월 (0=즉시 지급분)
    pct       NUMBER(9,6) NOT NULL,     -- 해당 시점 지급 비율 (합계 1.000000)
    CONSTRAINT pk_deferral_curve_dtl PRIMARY KEY (curve_id, month_no),
    CONSTRAINT fk_curve_dtl FOREIGN KEY (curve_id) REFERENCES DEFERRAL_CURVE (curve_id)
);

CREATE TABLE DEFERRAL_SCHEDULE (
    schedule_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_calc_id   NUMBER       NOT NULL,
    policy_no        VARCHAR2(30) NOT NULL,
    agent_id         VARCHAR2(20) NOT NULL,
    due_ym           VARCHAR2(6)  NOT NULL,
    amount           NUMBER(15)   NOT NULL,
    pay_condition    VARCHAR2(30) NOT NULL,   -- 예: POLICY_INFORCE (해당월 유지 시 지급)
    status           VARCHAR2(12) NOT NULL,   -- SCHEDULED/RELEASED/HELD/CANCELLED
    curve_version_id NUMBER       NOT NULL,
    released_calc_id NUMBER,                  -- RELEASED 시 생성된 COMM_CALC 참조 (멱등성)
    CONSTRAINT fk_defer_source FOREIGN KEY (source_calc_id) REFERENCES COMM_CALC (calc_id),
    CONSTRAINT ck_defer_status CHECK (status IN ('SCHEDULED','RELEASED','HELD','CANCELLED'))
);
CREATE INDEX ix_defer_due ON DEFERRAL_SCHEDULE (due_ym, status);
CREATE INDEX ix_defer_policy ON DEFERRAL_SCHEDULE (policy_no, agent_id);
