-- =====================================================================
-- V5: 환수 룰 / 환수 채권 (설계서 §5.8)
-- =====================================================================

CREATE TABLE CLAWBACK_RULE (
    rule_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_key      VARCHAR2(40),            -- NULL = 전 상품 공통
    event_type       VARCHAR2(20) NOT NULL,   -- CANCEL/LAPSE/WITHDRAW/REDUCE
    from_installment NUMBER(3)    NOT NULL,   -- 경과 회차 구간 시작 (포함)
    to_installment   NUMBER(3)    NOT NULL,   -- 경과 회차 구간 끝 (포함)
    clawback_pct     NUMBER(9,6)  NOT NULL,   -- 환수율
    apply_from       DATE         NOT NULL,   -- 계약 체결일 기준
    apply_to         DATE         DEFAULT DATE '9999-12-31' NOT NULL
);
CREATE INDEX ix_clawback_rule ON CLAWBACK_RULE (event_type, apply_from);

-- 지급액보다 환수가 크면 채권으로 이월·상계
CREATE TABLE CLAWBACK_RECEIVABLE (
    receivable_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id       VARCHAR2(20) NOT NULL,
    origin_calc_id NUMBER,
    amount         NUMBER(15)   NOT NULL,
    remaining      NUMBER(15)   NOT NULL,
    status         VARCHAR2(12) NOT NULL,     -- OPEN/OFFSET/CLOSED/WRITTEN_OFF
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recv_calc FOREIGN KEY (origin_calc_id) REFERENCES COMM_CALC (calc_id),
    CONSTRAINT ck_recv_status CHECK (status IN ('OPEN','OFFSET','CLOSED','WRITTEN_OFF'))
);
CREATE INDEX ix_recv_agent ON CLAWBACK_RECEIVABLE (agent_id, status);

-- 채권 상계 이력 (어느 지급에서 얼마를 상계했는지)
CREATE TABLE CLAWBACK_OFFSET_HIST (
    offset_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receivable_id NUMBER     NOT NULL,
    calc_id       NUMBER     NOT NULL,
    amount        NUMBER(15) NOT NULL,
    offset_at     TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_offset_recv FOREIGN KEY (receivable_id) REFERENCES CLAWBACK_RECEIVABLE (receivable_id),
    CONSTRAINT fk_offset_calc FOREIGN KEY (calc_id) REFERENCES COMM_CALC (calc_id)
);
