-- =====================================================================
-- V6: 마감/조정 + 설계사/조직 마스터 최소본 (설계서 §5.9, §2.4)
-- =====================================================================

CREATE TABLE SETTLE_CLOSE (
    close_ym  VARCHAR2(6)  PRIMARY KEY,
    status    VARCHAR2(12) NOT NULL,     -- OPEN/CLOSING/CLOSED
    closed_at TIMESTAMP,
    closed_by VARCHAR2(20),
    CONSTRAINT ck_close_status CHECK (status IN ('OPEN','CLOSING','CLOSED'))
);

-- 마감 후 정정: 반드시 익월 귀속
CREATE TABLE ADJUSTMENT (
    adj_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_calc_id NUMBER,
    reason         VARCHAR2(200) NOT NULL,
    amount         NUMBER(15)    NOT NULL,
    close_ym       VARCHAR2(6)   NOT NULL,
    approved_by    VARCHAR2(20),
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adj_calc FOREIGN KEY (target_calc_id) REFERENCES COMM_CALC (calc_id)
);

-- 설계사 마스터 + 등급/소속 이력 (수급자 결정·지급률 조회용 최소본)
CREATE TABLE AGENT_MST (
    agent_id     VARCHAR2(20) PRIMARY KEY,
    agent_name   VARCHAR2(50) NOT NULL,
    appointed_on DATE         NOT NULL,   -- 위촉일
    dismissed_on DATE                     -- 해촉일 (NULL=재직)
);

CREATE TABLE AGENT_GRADE_HIST (
    agent_id   VARCHAR2(20) NOT NULL,
    grade_cd   VARCHAR2(10) NOT NULL,
    apply_from DATE         NOT NULL,
    apply_to   DATE         DEFAULT DATE '9999-12-31' NOT NULL,
    CONSTRAINT pk_agent_grade PRIMARY KEY (agent_id, apply_from),
    CONSTRAINT fk_grade_agent FOREIGN KEY (agent_id) REFERENCES AGENT_MST (agent_id)
);

-- 조직 트리 (본부-지점-팀) + 설계사 소속 이력
CREATE TABLE ORG_MST (
    org_id     VARCHAR2(20) PRIMARY KEY,
    org_name   VARCHAR2(50) NOT NULL,
    org_level  VARCHAR2(10) NOT NULL,     -- HQ/BRANCH/TEAM
    parent_org VARCHAR2(20),
    CONSTRAINT fk_org_parent FOREIGN KEY (parent_org) REFERENCES ORG_MST (org_id),
    CONSTRAINT ck_org_level CHECK (org_level IN ('HQ','BRANCH','TEAM'))
);

CREATE TABLE AGENT_ORG_HIST (
    agent_id   VARCHAR2(20) NOT NULL,
    org_id     VARCHAR2(20) NOT NULL,
    apply_from DATE         NOT NULL,
    apply_to   DATE         DEFAULT DATE '9999-12-31' NOT NULL,
    CONSTRAINT pk_agent_org PRIMARY KEY (agent_id, apply_from),
    CONSTRAINT fk_aoh_agent FOREIGN KEY (agent_id) REFERENCES AGENT_MST (agent_id),
    CONSTRAINT fk_aoh_org FOREIGN KEY (org_id) REFERENCES ORG_MST (org_id)
);

-- 조직 오버라이드 배분율 (계층별 요율, 유효기간 버전)
CREATE TABLE ORG_OVERRIDE_RATE (
    org_level  VARCHAR2(10) NOT NULL,
    comm_type  VARCHAR2(20) NOT NULL,     -- 어느 수수료 유형에 대한 오버라이드인가
    override_rate NUMBER(9,6) NOT NULL,
    apply_from DATE          NOT NULL,
    apply_to   DATE          DEFAULT DATE '9999-12-31' NOT NULL,
    CONSTRAINT pk_org_override PRIMARY KEY (org_level, comm_type, apply_from)
);
