-- =====================================================================
-- V7: Phase 10 보강 — 마감 정산 내역 원장, INBOUND 명세 원장, 이벤트 실패 사유
--   (기존 포트 AgentSettlementStore / InboundStatementStore / PolicyEventStore.markFailed의
--    영속화 대상 테이블. 설계서 §5 부가 테이블 목록의 실체화)
-- =====================================================================

-- 이벤트 처리 실패 사유 (markFailed) — 진단용 텍스트. ''와 NULL을 구분하지 않는다 (§8.7)
ALTER TABLE POLICY_EVENT ADD fail_reason VARCHAR2(400);

-- 마감 시 확정된 수급자별 월 정산 내역 (SettlementRow) — 지급 배치의 입력
CREATE TABLE AGENT_SETTLEMENT (
    settlement_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    close_ym           VARCHAR2(6)  NOT NULL,
    recipient_type     VARCHAR2(10) NOT NULL,
    recipient_id       VARCHAR2(20) NOT NULL,
    gross_net          NUMBER(15)   NOT NULL,   -- 당월 계산 순액 (전 상태 합산, §3.0)
    receivable_offset  NUMBER(15)   NOT NULL,   -- 기존 채권 자동 상계액
    carried_receivable NUMBER(15)   NOT NULL,   -- 음수 순액의 채권 이월분 (양수 표기)
    payable            NUMBER(15)   NOT NULL,
    created_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_settle_recipient CHECK (recipient_type IN ('AGENT', 'ORG'))
);
CREATE INDEX ix_agent_settlement_ym ON AGENT_SETTLEMENT (close_ym);

-- 정산 내역 ↔ 근거 계산 레코드 (SettlementRow.calcIds, 순서 보존)
CREATE TABLE AGENT_SETTLEMENT_CALC (
    settlement_id NUMBER NOT NULL,
    calc_seq      NUMBER NOT NULL,
    calc_id       NUMBER NOT NULL,
    CONSTRAINT pk_settlement_calc PRIMARY KEY (settlement_id, calc_seq),
    CONSTRAINT fk_sc_settlement FOREIGN KEY (settlement_id) REFERENCES AGENT_SETTLEMENT (settlement_id),
    CONSTRAINT fk_sc_calc FOREIGN KEY (calc_id) REFERENCES COMM_CALC (calc_id)
);

-- 정규화된 보험사 수수료 명세 원장 (InboundStatement) — statement_key 멱등 저장
CREATE TABLE INBOUND_STATEMENT (
    statement_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_key  VARCHAR2(120) NOT NULL,
    insurer_cd     VARCHAR2(10)  NOT NULL,
    statement_ym   VARCHAR2(6)   NOT NULL,
    policy_no      VARCHAR2(30)  NOT NULL,
    product_key    VARCHAR2(40)  NOT NULL,
    comm_type      VARCHAR2(20)  NOT NULL,
    installment_no NUMBER(3),
    amount         NUMBER(15)    NOT NULL,
    raw_fields     CLOB,                        -- 원문 필드 JSON (Oracle: IS JSON 체크는 V100)
    received_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_inbound_statement_key UNIQUE (statement_key)
);
CREATE INDEX ix_inbound_ym_insurer ON INBOUND_STATEMENT (statement_ym, insurer_cd);
