-- =====================================================================
-- V8: Phase 10b — 룰 마스터·조직 어댑터 보강
--   ① 룰 변경 이력 (설계서 §6.6 v1.1.2 — 트리밍 UPDATE의 변경 감사)
--   ② 요율 ID 시퀀스 (CommRateAdminStore.nextRateId 포트용)
--   ③ AGENT_ORG_HIST PK 교정 — 팀+지점+본부 체인(설계사×기간당 여러 소속 행)을
--      담을 수 있도록 (agent_id, apply_from) → (agent_id, org_id, apply_from)
-- =====================================================================

-- ① 트리밍/전이 감사: 변경 전후 값·변경자·시각 (시스템 시간축, §3.1)
CREATE TABLE COMM_RATE_CHANGE_HIST (
    change_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_id      NUMBER       NOT NULL,
    change_type  VARCHAR2(12) NOT NULL,   -- TRIM/SUPERSEDE/ACTIVATE/DISCARD
    old_apply_to DATE         NOT NULL,
    new_apply_to DATE         NOT NULL,
    old_status   VARCHAR2(10) NOT NULL,
    new_status   VARCHAR2(10) NOT NULL,
    changed_by   VARCHAR2(20) NOT NULL,
    changed_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_rate_hist FOREIGN KEY (rate_id) REFERENCES COMM_RATE (rate_id),
    CONSTRAINT ck_rate_hist_type CHECK (change_type IN ('TRIM', 'SUPERSEDE', 'ACTIVATE', 'DISCARD'))
);
CREATE INDEX ix_rate_hist_rate ON COMM_RATE_CHANGE_HIST (rate_id);

-- ② 승인 워크플로용 요율 ID 채번. COMM_RATE.rate_id는 identity(BY DEFAULT)라
--    시드/수기 등록(작은 ID 대역)과 충돌하지 않도록 1,000,000부터 시작한다.
CREATE SEQUENCE COMM_RATE_ADMIN_SEQ START WITH 1000000 INCREMENT BY 1;

-- ③ 소속 이력 PK 교정 — 같은 (설계사, 개시일)에 팀/지점/본부 3행이 공존해야 한다
ALTER TABLE AGENT_ORG_HIST DROP CONSTRAINT pk_agent_org;
ALTER TABLE AGENT_ORG_HIST ADD CONSTRAINT pk_agent_org
    PRIMARY KEY (agent_id, org_id, apply_from);
